-- MySQL Script generated by MySQL Workbench
-- Sat Jul 24 13:50:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test_task_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_task_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_task_schema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test_task_schema` ;

-- -----------------------------------------------------
-- Table `test_task_schema`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_task_schema`.`posts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1046
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_task_schema`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_task_schema`.`comments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `postId` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `body` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `postId_idx` (`postId` ASC) VISIBLE,
  CONSTRAINT `postId`
    FOREIGN KEY (`postId`)
    REFERENCES `test_task_schema`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1032
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
